<a href="https://colab.research.google.com/github/Aashrawat/machine-learning/blob/main/NLP_ML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [7]:
df = pd.read_csv('train.txt',sep = ';', header = None, names = ['text','emotion'])

In [8]:
df.head()

                                                text  emotion
0                            i didnt feel humiliated  sadness
1  i can go from feeling so hopeless to so damned...  sadness
2   im grabbing a minute to post i feel greedy wrong    anger
3  i am ever feeling nostalgic about the fireplac...     love
4                               i am feeling grouchy    anger

In [9]:
## converting emotion in numbers
df.isnull().sum()

text       0
emotion    0
dtype: int64

In [10]:
unique_emotions = df['emotion'].unique()
emotion_numbers = {}##create a dictionary
i = 0
for emotion in unique_emotions:
    emotion_numbers[emotion]=i
    i+=1

df['emotion'] = df['emotion'].map(emotion_numbers)

In [11]:
df

                                                    text  emotion
0                                i didnt feel humiliated        0
1      i can go from feeling so hopeless to so damned...        0
2       im grabbing a minute to post i feel greedy wrong        1
3      i am ever feeling nostalgic about the fireplac...        2
4                                   i am feeling grouchy        1
...                                                  ...      ...
15995  i just had a very brief time in the beanbag an...        0
15996  i am now turning and i feel pathetic that i am...        0
15997                     i feel strong and good overall        5
15998  i feel like this was such a rude comment and i...        1
15999  i know a lot but i feel so stupid because i ca...        0

[16000 rows x 2 columns]

In [12]:
df['text']=df['text'].apply(lambda x:x.lower())## into lower case

In [13]:
import string  ## remove punc
def remove_punc(txt):
  return txt.translate(str.maketrans('','',string.punctuation))

In [14]:
df['text']=df['text'].apply(remove_punc)

In [15]:
def remove_numbers(txt): ## remove numbers
  new =''
  for i in txt:
    if not i.isdigit():
      new = new +i
  return new
df['text']=df['text'].apply(remove_numbers)

In [16]:
def remove_emojis(txt):## remove emojis
  new =""
  for i in txt:
    if i.isascii():
      new = new +i
  return new
df['text']=df['text'].apply(remove_emojis)

In [17]:
## remove stopwords use library like NLTK NATURAL LANGUAGE LANGUAGE TOOLKIT
import nltk

In [18]:
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

In [19]:
nltk.download('punkt')
nltk.download('stopwords')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

True

In [20]:
stop_words = set(stopwords.words('english'))
len(stop_words)

198

In [21]:
df.loc[1]['text']

'i can go from feeling so hopeless to so damned hopeful just from being around someone who cares and is awake'

In [22]:
def remove(txt):
  words = txt.split()
  cleaned = []
  for word in words:
    if word not in stop_words:
      cleaned.append(word)
  return ' '.join(cleaned)

In [23]:
df['text']=df['text'].apply(remove)

In [24]:
df.loc[1]['text']

'go feeling hopeless damned hopeful around someone cares awake'

In [25]:
df.head()

                                                text  emotion
0                              didnt feel humiliated        0
1  go feeling hopeless damned hopeful around some...        0
2          im grabbing minute post feel greedy wrong        1
3  ever feeling nostalgic fireplace know still pr...        2
4                                    feeling grouchy        1

In [26]:
from sklearn.model_selection import train_test_split

X_train,X_test, y_train, y_test = train_test_split(df['text'], df['emotion'], test_size = 0.2, random_state = 42)

In [28]:
X_train

676      refers course though cant help feeling somehow...
12113                im starting feel im suffering fatigue
7077     feel like probably would liked book little bit...
13005                                  really feel awkward
12123    im feeling little grumpy today lame weather te...
                               ...
13418    love leave reader feeling confused slightly de...
5390                                         feel delicate
860                          starting feel little stressed
15795             feel stressed tired worn shape neglected
7270         feel someone rude wrongly done something lose
Name: text, Length: 12800, dtype: object

In [30]:
df.shape

(16000, 2)

In [32]:
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer
from sklearn.naive_bayes import MultinomialNB ## for text classification we use Multinomial NB
from sklearn.metrics import accuracy_score

In [33]:
bow_vectorizer = CountVectorizer()
X_train_bow = bow_vectorizer.fit_transform(X_train)

X_test_bow = bow_vectorizer.transform(X_test)

nb_model = MultinomialNB()
nb_model.fit(X_train_bow, y_train)

pred_bow = nb_model.predict(X_test_bow)
print(accuracy_score(y_test, pred_bow))

0.768125

In [34]:
pred_bow

array([0, 5, 0, ..., 5, 5, 0])

In [35]:
tfidf_vectorizer = TfidfVectorizer()
X_train_tfidf = tfidf_vectorizer.fit_transform(X_train)
X_test_tfidf = tfidf_vectorizer.transform(X_test)


nb2_model = MultinomialNB()
nb2_model.fit(X_train_tfidf,y_train)

MultinomialNB()

In [36]:
y_pred = nb2_model.predict(X_test_tfidf)

In [37]:
print(accuracy_score(y_test,y_pred))

0.6609375

In [38]:
from sklearn.linear_model import LogisticRegression

In [40]:
logistic_model = LogisticRegression(max_iter = 1000)
logistic_model.fit(X_train_tfidf,y_train)

LogisticRegression(max_iter=1000)

In [41]:
log_pred = logistic_model.predict(X_test_tfidf)

In [42]:
print(accuracy_score(y_test,log_pred))

0.8628125